plugins {
  id 'java-library'
	id 'maven-publish'
	id 'io.freefair.lombok' version "9.8.0" 
  id "com.diffplug.spotless" version "8.10.4"
}

sourceSets {
  main {
    java.srcDirs = ['src/main']
  }
  test {
    java.srcDirs = ['src/test']
  }
}

repositories {
  mavenCentral()
}

java {
  withSourcesJar()
  withJavadocJar()
  toolchain {
    languageVersion = JavaLanguageVersion.of(25)
  }
}

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
  options.encoding = 'UTF-8'
  options.tags('apiNote:a:API Note:', 'implSpec:a:Implementation Requirements:', 'implNote:a:Implementation Note:')
}

check.dependsOn(javadoc)

lombok {
  version = '1.18.42'
}

dependencies {
  testImplementation(platform('org.junit:junit-bom:5.10.2'))
  testImplementation('org.junit.jupiter:junit-jupiter')
  testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

tasks.withType(Test).configureEach {
  useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
						from components.java
            pom {
                name = 'tabbie-sdk'
                description = 'Software Development Kit for Tabbie'
                url = 'https://github.com/Jelatinone/tabbie-sdk'
                licenses {
                    license {
                        name = 'The Apache License, Version 2.0'
                        url = 'http://www.apache.org/licenses/LICENSE-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'jelatinone'
                        name = 'Cody Washington'
                        email = 'washington.cody@proton.me'
                    }
                }
                scm {
                    connection = 'scm:git:https://github.com/Jelatinone/tabbie-sdk.git'
                    url = 'https://github.com/Jelatinone/tabbie-sdk'
                }
            }
        }
    }
}

spotless {
  java {
    target 'src/**/*.java'
    targetExclude 'src/**/external/**/*.java'

    toggleOffOn()
    removeUnusedImports()
    importOrder('com', 'org', 'java', '', '#').wildcardsLast()
    setEncoding('UTF-8')
    leadingTabsToSpaces(2)
    trimTrailingWhitespace()
    endWithNewline()
  }

  groovyGradle {
    target '*.gradle'

    greclipse()
    leadingTabsToSpaces(2)
    trimTrailingWhitespace()
    endWithNewline()
  }
}
build.dependsOn(spotlessApply)